Tamirhane/Tamirhane.WebUI/Controllers/CustomerCarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tamirhane.Data;

namespace Tamirhane.WebUI.Controllers
{
    public class CustomerCarController : Controller
    {
        private TamirhaneContext db = new TamirhaneContext();

        public ActionResult CustomerSearchbyPlate(string Plate,int CustomerId)
        {
            var c = db.CustomerCar.Where(x => x.CustomerId == CustomerId && x.Plate.Contains(Plate)).Select(x => new { Plate = x.Plate, Id = x.Id }).OrderBy(x => x.Id).Skip(0).Take(5).ToList();
            return Json(c, JsonRequestBehavior.AllowGet);
        }


        // GET: CustomerCar
        public ActionResult Index(int CustomerId = 0)
        {
            var customerCar = db.CustomerCar.Include(c => c.Customer);
            if (CustomerId>0)
            {
                customerCar = customerCar.Where(x => x.CustomerId == CustomerId);
            }

            return View(customerCar.ToList());
        }

        // GET: CustomerCar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerCar customerCar = db.CustomerCar.Find(id);
            if (customerCar == null)
            {
                return HttpNotFound();
            }
            return View(customerCar);
        }

        // GET: CustomerCar/Create
        public ActionResult Create(int CustomerId = 0)
        {
          
            var model = new CustomerCar();
            if (CustomerId>0)
            {
                model.Customer = db.Customer.FirstOrDefault(x => x.Id == CustomerId);
            }

            return View(model);
        }


        // POST: CustomerCar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Plate,Brand,Model,ModelYear,CustomerId,UpdatedDate,CreatedDate")] CustomerCar customerCar)
        {
            
            if (ModelState.IsValid)
            {
                db.CustomerCar.Add(customerCar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            if (customerCar.CustomerId > 0)
            {
                customerCar.Customer = db.Customer.FirstOrDefault(x => x.Id == customerCar.CustomerId);
            }

            return View(customerCar);
        }

        // GET: CustomerCar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerCar customerCar = db.CustomerCar.Include("Customer").FirstOrDefault(x=>x.Id ==id);
            if (customerCar == null)
            {
                return HttpNotFound();
            }

         

            return View(customerCar);
        }

        // POST: CustomerCar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Plate,Brand,Model,ModelYear,CustomerId,UpdatedDate,CreatedDate")] CustomerCar customerCar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customerCar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            if (customerCar.CustomerId > 0)
            {
                customerCar.Customer = db.Customer.FirstOrDefault(x => x.Id == customerCar.CustomerId);
            }
            string s = "";

            return View(customerCar);
        }

        // GET: CustomerCar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerCar customerCar = db.CustomerCar.Find(id);
            if (customerCar == null)
            {
                return HttpNotFound();
            }
            return View(customerCar);
        }

        // POST: CustomerCar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomerCar customerCar = db.CustomerCar.Find(id);
            db.CustomerCar.Remove(customerCar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tamirhane/Tamirhane.WebUI/Controllers/CustomerController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tamirhane.Data;
using Tamirhane.WebUI.App_Start;

namespace Tamirhane.WebUI.Controllers
{
    public class CustomerController : Controller
    {
        private TamirhaneContext db = new TamirhaneContext();
        public ActionResult CustomerSearchbyName(string FullName)
        {
            var c = db.Customer.Where(x=>x.FullName.Contains(FullName)).OrderBy(x=>x.FullName).Skip(0).Take(5).Select(x => new { CustomerId = x.Id, Title = x.Name + " " + x.LastName }).ToList();
            return Json(c, JsonRequestBehavior.AllowGet);
        }


        // GET: Customers
        public ActionResult Index(int page=1)
        {
            var customers = db.Customer.ToList();
            PagedList<Customer> model = new PagedList<Customer>(customers, page, TamirhaneAppContext.DefaultPageSize);
            return View(model);
        }


        // GET: Customers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,LastName,Email,Phone,UpdatedDate,CreatedDate")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.FullName = customer.Name + " " + customer.LastName;
                db.Customer.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,LastName,Email,Phone,UpdatedDate,CreatedDate")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                customer.FullName = customer.Name + " " + customer.LastName;
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customer.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customer.Find(id);
            db.Customer.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tamirhane/Tamirhane.WebUI/Views/Customer/Create.cshtml
@model Tamirhane.Data.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Müşteri Oluştur</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Müşteri Listesi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tamirhane/Tamirhane.WebUI/Views/Customer/Delete.cshtml
@model Tamirhane.Data.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tamirhane/Tamirhane.WebUI/Views/Customer/Details.cshtml
@model Tamirhane.Data.Customer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tamirhane/Tamirhane.WebUI/Views/Customer/Edit.cshtml
@model Tamirhane.Data.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Müşteri Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CreatedDate)
    @Html.HiddenFor(model => model.UpdatedDate)
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Müşteri Listesi", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tamirhane/Tamirhane.WebUI/Views/Customer/Index.cshtml
@model PagedList.IPagedList<Tamirhane.Data.Customer>
@{
    ViewBag.Title = "Müşteri Listesi";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Müşteri Ekle", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Phone)
        </th>
       
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Araç Ekle", "Create", "CustomerCar", new { CustomerId = item.Id }, null) |
                @Html.ActionLink("Araç Listesi", "Index", "CustomerCar", new { CustomerId = item.Id }, null) |
                @Html.ActionLink("Detay", "Details", new { id = item.Id }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, pageSize = TamirhaneAppContext.DefaultPageSize }))