Tamirhane/Tamirhane.WebUI/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tamirhane.Data;

namespace Tamirhane.WebUI.Controllers
{
    public class AppointmentController : Controller
    {
        private TamirhaneContext db = new TamirhaneContext();

        // GET: Appointment
        public ActionResult Index()
        {
            var appointment = db.Appointment.Include(a => a.CustomerCar).Include(x=>x.WorkOrder).Include(x=>x.Customer);
            return View(appointment.ToList());
        }

        // GET: Appointment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointment.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // GET: Appointment/Create
        public ActionResult Create()
        {
            var model = new Appointment();
            model.AppointmentDate = DateTime.Now;
            ViewBag.CustomerCarId = new SelectList(db.CustomerCar, "Id", "Plate");
            return View(model);
        }

        // POST: Appointment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Appointment.Add(appointment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(appointment);
        }

        // GET: Appointment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointment.Include("Customer").Include("CustomerCar").FirstOrDefault(x=>x.Id==id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
          
            return View(appointment);
        }

        // POST: Appointment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(appointment);
        }

        // GET: Appointment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointment.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // POST: Appointment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Appointment appointment = db.Appointment.Find(id);
            db.Appointment.Remove(appointment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tamirhane/Tamirhane.WebUI/Controllers/WorkOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tamirhane.Data;

namespace Tamirhane.WebUI.Controllers
{
    public class WorkOrderController : Controller
    {
        private TamirhaneContext db = new TamirhaneContext();

        // GET: WorkOrder
        public ActionResult Index()
        {
            var workOrder = db.WorkOrder.Include(x=>x.Appointment).Include(w => w.CustomerCar).Include(x=>x.Customer);
            return View(workOrder.ToList());
        }

        // GET: WorkOrder/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = db.WorkOrder.Find(id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }

        // GET: WorkOrder/Create
        public ActionResult Create(int AppointmentId = 0)
        {
            var model = new WorkOrder();
            if (AppointmentId>0)
            {
                var app = db.Appointment.Include("CustomerCar").Include("Customer").FirstOrDefault(x => x.Id == AppointmentId);
                model.AppointmentInfo = app.AppointmentDate.ToString() + " " + app.AppointmentDescription;
                model.CustomerCar = app.CustomerCar;
                model.Customer = app.Customer;
                model.CustomerCarId = app.CustomerCar.Id;
                model.CustomerId= app.CustomerCar.CustomerId;

            }
            return View(model);
        }

        // POST: WorkOrder/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WorkOrder model, int AppointmentId = 0)
        {
            
            if (ModelState.IsValid)
            {
                db.WorkOrder.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (AppointmentId > 0)
            {
                var app = db.Appointment.Include("CustomerCar").Include("Customer").FirstOrDefault(x => x.Id == AppointmentId);
                model.AppointmentInfo = app.AppointmentDate.ToString() + " " + app.AppointmentDescription;
                model.CustomerCar = app.CustomerCar;
                model.Customer = app.Customer;
            }
            return View(model);
        }

        // GET: WorkOrder/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = db.WorkOrder.Include("Customer").Include("CustomerCar").Include("Appointment").FirstOrDefault(x=>x.Id==id);
            if (workOrder.Appointment != null)
            {
                var app = workOrder.Appointment;
                workOrder.AppointmentInfo = app.AppointmentDate.ToString() + " " + app.AppointmentDescription;
            }
        
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }

        // POST: WorkOrder/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( WorkOrder workOrder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workOrder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(workOrder);
        }

        // GET: WorkOrder/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkOrder workOrder = db.WorkOrder.Include("CustomerCar").Include("Appointment").FirstOrDefault(x=>x.Id ==id);
            if (workOrder == null)
            {
                return HttpNotFound();
            }
            return View(workOrder);
        }

        // POST: WorkOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkOrder workOrder = db.WorkOrder.Find(id);
            db.WorkOrder.Remove(workOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tamirhane/Tamirhane.WebUI/Views/Appointment/Create.cshtml
@model Tamirhane.Data.Appointment

@{
    ViewBag.Title = "Randevu Oluştur";
}

<h2>Randevu Oluştur</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.Partial("_CustomerCarCreateOrEdit", Model)
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tamirhane/Tamirhane.WebUI/Views/Appointment/Delete.cshtml
@model Tamirhane.Data.Appointment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerCar.Plate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerCar.Plate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppointmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppointmentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tamirhane/Tamirhane.WebUI/Views/Appointment/Details.cshtml
@model Tamirhane.Data.Appointment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerCar.Plate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerCar.Plate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AppointmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AppointmentDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tamirhane/Tamirhane.WebUI/Views/Appointment/Edit.cshtml
@model Tamirhane.Data.Appointment

@{
    ViewBag.Title = "Edit";
}

<h2>Randevu Düzenle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
     @Html.Partial("_CustomerCarCreateOrEdit",Model)
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tamirhane/Tamirhane.WebUI/Views/Appointment/Index.cshtml
@model IEnumerable<Tamirhane.Data.Appointment>

@{
    ViewBag.Title = "Index";
}

<h2>Randevu Listesi</h2>

<p>
    @Html.ActionLink("Yeni Randevu Oluştur", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerCar.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerCar.Plate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AppointmentDate)
        </th>

        <th>
            İş Emri / Onay Bilgisi
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerCar.Plate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AppointmentDate)
        </td>
      
        <td>
            @string.Join(",", item.WorkOrder.Select(x => x.CreatedDate))
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Detay", "Details", new { id = item.Id }) |
            @Html.ActionLink("İş Emri Oluştur / Onayla", "Create", "WorkOrder", new { AppointmentId = item.Id, }, null) |
            @Html.ActionLink("Sil", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

Tamirhane/Tamirhane.WebUI/Views/Appointment/_CustomerCarCreateOrEdit.cshtml
@model Tamirhane.Data.Appointment
@{
    var fullName = "";
    if (Model.Customer !=null)
    {
        fullName = Model.Customer.FullName;
    }
    var plate = "";
    if (Model.CustomerCar != null)
    {
        plate = Model.CustomerCar.Plate;
    }
}

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input id="CustomerAutoComplate" class="form-control" value="@fullName" )>
            @Html.HiddenFor(x => x.CustomerId)
            @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CustomerCarId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input id="CustomerCarIdAutoComplate" class="form-control" value="@plate">
            @Html.HiddenFor(x => x.CustomerCarId)
            @Html.ValidationMessageFor(model => model.CustomerCarId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AppointmentDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AppointmentDescription, new { htmlAttributes = new { @class = "form-control " } })
            @Html.ValidationMessageFor(model => model.AppointmentDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AppointmentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AppointmentDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
            @Html.ValidationMessageFor(model => model.AppointmentDate, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}